### ISSUE TITLE
question: how to use custom hyperkube build with kubeup

### ISSUE THREAD

**Issue by colemickens** [lpabon/kubeup#3]
Thanks! This took less than 10 minutes to get running in Arch with some small modifications!

One small question: I'm not totally familiar with this usage of `bootkube`. How would I go about having this deployment use a custom build of `hyperkube` for both the control plane components in `bootkube` as well as for the node `kubelet`s as well?

**Comment by colemickens** [comment]
I think I see there's just a simple invocation of `bootkube` in `bootstrap.sh`. I think I have something working locally that makes it a bit easier to do. When I confirm it, I'll send a PR here.

**Comment by lpabon** [comment]
@colemickens Hey, I just changed to use vagrant/libvirt and kubeadm. So it should work just fine in Arch.
